version: 2
updates:
  - package-ecosystem: npm
    directory: /
    labels:
      - Dependency
    groups:
      production-deps:
        dependency-type: production
      development-deps:
        dependency-type: development
    versioning-strategy: increase
    schedule:
      interval: weekly
      day: wednesday
      time: "12:00"
      timezone: Canada/Mountain
