name: Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
      - id: setup-nodejs
        name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - id: install-dependencies
        name: Install dependencies
        run: npm install
      - id: run-linter
        name: Run linter
        run: npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
      - id: setup-nodejs
        name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - id: install-dependencies
        name: Install dependencies
        run: npm install
      - id: run-build
        name: Run build
        run: npm run build
      - id: run-tests
        name: Run tests
        run: npm run test:ci
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - id: checkout-repository
        name: Checkout repository
        uses: actions/checkout@v4
      - id: setup-nodejs
        name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - id: install-dependencies
        name: Install dependencies
        run: npm install
      - id: run-build
        name: Run build
        run: npm run build
